### ISSUE TITLE
Referencing of OpenSustain.tech 

### ISSUE THREAD

**Issue by Ly0n** [Pierre-VF/oss4climate#110]
Hey @Pierre-VF,

Looks really cool what you have built here. Could you please refer to OpenSustain.tech on the website as you are scraping most of the data from our website and our license demands that. I have invested over 3000 hours in maintaining, researching and promoting and without further curation of the original dataset, this effort will simply die. It would also be cool to have a chat next year to join both efforts so that both projects are kept going in the long term.

**Comment by Pierre-VF** [comment]
Hey @Ly0n ,
Thanks for reaching out and the huge work of your team (I'm by no means aiming at competing but making it - among other listings - accessible in the longer run). 
OpenSustain is actually mentioned here together with the other repos that are indexed: https://github.com/Pierre-VF/oss4climate/blob/main/indexes/listings.toml (but I indeed saw that the link was not properly activated in the README), thanks for flagging that up. The aim was indeed to credit all the sources (also those where the licences are not requiring it)
I'll send you a direct email for the discussion part 😸

**Comment by Ly0n** [comment]
Yes but the dataset is almost entirely our dataset. For example here: 

[faults]
urls = [
    "http://sciencepolicy.colorado.edu/icecaps/research/media_coverage/",
    "https://archive.ceda.ac.uk/",
    "https://cds.climate.copernicus.eu/",
    "https://climate.esa.int/en/odp/",
    "https://data.apps.fao.org/",
    "https://data.subak.org/",
    "https://db.cger.nies.go.jp/portal/geds/index",
    "https://energy.acm.org/resources/",
    "https://globalenergymonitor.org/",
    "https://globalfishingwatch.org/",
    "https://globalsolaratlas.info/",
    "https://globalwindatlas.info/",
    "https://maps.opendatascience.eu/",
    "https://podaac.jpl.nasa.gov/cloud-datasets",
    "https://power.larc.nasa.gov/",
    "https://wiki.openmod-initiative.org/wiki/Open_Models",
    "https://www.earthdata.nasa.gov/",
]

These are the links that we have listed on OpenSustain.tech and are not repositories. You remove them here. You also add other repositories from the larger namespaces we have identified in the past what is a smart move but this project have never been reviewed.

We are building multiple services like ClimateTriage.com and OpenClimate.fund around them and are already struggeling to keep this effort alive.  So please reference it in the frontend and we can have a propor conversation on how we could join our effort.

**Comment by Pierre-VF** [comment]
Yes, I agree - this is addressed in this PR that I am about to deploy https://github.com/Pierre-VF/oss4climate/pull/111
